<a href="https://colab.research.google.com/github/Konikakonika/PYTORCH_INTERN/blob/main/intern.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**FEED FORWARD IMPLEMENTATION**

In [25]:
import numpy as np

In [26]:
x=np.array([
    [1,0,1,0],
    [1,0,1,1],
    [0,1,0,1]
])
y=np.array([[1],[1],[0]])

In [27]:
#activation function
def sigmoid(x):
  return 1 / (1+np.exp(-x))

In [28]:
x.shape#3 rows 4 column

(3, 4)

input layer k neuron equal to no of column
hidden neuron decide by hit nd trial
output is decide or depend on target column

In [29]:
inputNeurons =x.shape[1]#4 value hogyi , jitne no of column honge utne inputneurib honge
hiddenNeurons=4#value depend ni krti kisi pr
outputNeurons=1# ya to 1 ya 0 do hi output aaskte h

In [30]:
#weight matrix bnana h ,wh=[4,3] wo[3,1] bh[1,3] bo[1,1]

In [31]:
weightHidden= np.random.uniform(size=(inputNeurons,hiddenNeurons))
biasHidden= np.random.uniform(size=(1,hiddenNeurons))
weightOutput= np.random.uniform(size=(hiddenNeurons,outputNeurons))
biasOutput= np.random.uniform(size=(1,outputNeurons))

In [32]:
#feedforward
#step1-apply dot product and add bias:f(x)=x.wh+bias
np.dot(x,weightHidden)

array([[1.20940823, 0.77430122, 1.1249379 , 0.47117508],
       [1.63747519, 1.43652477, 1.36578517, 0.74618922],
       [0.61876496, 1.23189367, 0.87176937, 1.22528571]])

In [33]:
fx=np.dot(x,weightHidden)+biasHidden

In [34]:
fx

array([[1.5000723 , 1.44249334, 1.12718552, 1.13523388],
       [1.92813925, 2.10471689, 1.36803279, 1.41024802],
       [0.90942903, 1.9000858 , 0.87401698, 1.88934451]])

In [35]:
#step-2: apply activation function
hiddenLayer=sigmoid(fx)

In [36]:
hiddenLayer

array([[0.81758526, 0.80884046, 0.75531912, 0.7568035 ],
       [0.87304332, 0.89136079, 0.79706213, 0.80380506],
       [0.71288331, 0.86990124, 0.70558086, 0.86868077]])

In [37]:
#step-3; apply dot prod. and add bias :fx=hiddenlayer.wout+biasout
fx_=np.dot(hiddenLayer,weightOutput)+biasOutput

In [38]:
fx_

array([[1.85359989],
       [1.94097975],
       [1.94427623]])

In [39]:
biasHidden

array([[0.29066407, 0.66819212, 0.00224762, 0.6640588 ]])

In [40]:
biasOutput

array([[0.6376998]])

In [41]:
outputLayer=sigmoid(fx_)

In [42]:
outputLayer# 1 1 0 dikhna chahiye pr 1 1 1 h to glt h

array([[0.86454922],
       [0.87445974],
       [0.87482118]])

In [43]:
outputLayer.shape

(3, 1)

**BACKPROPAGATION**

In [44]:
def derivativeSigmoid(x):
  return x*(1-x)

In [45]:
errorOutput=outputLayer - y
slopeOutput=derivativeSigmoid(outputLayer)
deltaOutput=errorOutput*slopeOutput

In [ ]:
#error on output layer
errorHidden=np.dot(deltaOutput,weightOutput)
#slope on ouput layer-derivative sigmoid
slopeHidden=derivativeSigmoid(hiddenLayer)
deltaHidden=errorHidden*slopeHidden #reverse matrix hogyi h (3,1)nd (3,1) h dot product ka rule nhi h yh 

In [46]:
errorHidden=np.dot(deltaOutput,weightOutput.T)#isiliy transpose liya humne
slopeHidden=derivativeSigmoid(hiddenLayer)
deltaHidden=errorHidden*slopeHidden